# Site settings
title: "Kevin George | Data Platform | Dublin, Ireland"
description: "Resume Kevin George, Data Engineer , SQL Server , MCSA "

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Kevin George"
resume_title:                   "Data Platform | Cloud Solution Architect"
#resume_contact_email:           ""
#resume_contact_telephone:       ""
#resume_contact_address:         "Rathfarnham Dublin"
resume_header_contact_info: "Dublin, Ireland"
resume_header_intro: "<p>Experienced Technical Data Architect with experience in Retail Banking, Workforce and Telephony industries. Having several years of hands-on experiences building and designing Data-platforms, CI/CD pipelines and integrations with 3rd party systems.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kgeorge314/resume"
  resume_twitter_url:           "http://twitter.com/kgeorge_314"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kgeorge314"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://kgeorge314.github.io/resume"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
